name: Build and Deploy Node.js App  

on:  
  push:  
    branches:  
      - main  

jobs:  
  build-and-deploy:  
    runs-on: ubuntu-latest  

    steps:  
      # Step 1: 检出代码  
      - name: Checkout code  
        uses: actions/checkout@v3  

      # Step 2: 设置 Node.js 环境  
      - name: Setup Node.js  
        uses: actions/setup-node@v3  
        with:  
          node-version: '18'  

      # Step 3: 安装依赖  
      - name: Install dependencies  
        run: |  
          npm install  
          sudo npm install pm2 -g  

      # Step 4: 登录到 Docker Hub  
      - name: Login to Docker Hub  
        uses: docker/login-action@v2  
        with:  
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_PAT }}  

      # Step 5: 创建并推送 Docker 映像  
      - name: Build and push Docker image  
        env:  
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  
        run: |  
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pplx:latest .  
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pplx:latest
